parallel-jobs = 1
compression-level = 9
remove-rv-integrations-checks = true
patches-source = "anddea/revanced-patches"
rv-brand = "anddea ReVanced"
enable-magisk-update = true

[YouTube]
build-mode = "both"
version = "auto"
excluded-patches = ""
included-patches = " 'MaterialYou' "
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "rvx-anddea"
arch = "both"

[YouTube-v20]
build-mode = "both"
version = "20.12.46"
excluded-patches = ""
included-patches = " 'MaterialYou' "
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "rvx-anddea-v20"
arch = "both"

[Music]
build-mode = "both"
version = "auto"
included-patches = " 'MaterialYou' "
excluded-patches = ""
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "rvx-music-anddea"
arch = "both"
